CREATE ROLE wnba_data_user WITH login password 'password';

CREATE DATABASE wnba_data WITH owner wnba_data_user;

-- Connect to WNBA Data DB

SET ROLE TO wnba_data_user;

CREATE schema wnba_data_user AUTHORIZATION wnba_data_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

-- Create Tables and set Table Owner 

--
-- Table structure dataset_info
--
CREATE TABLE IF NOT EXISTS  dataset_info (
    date_generated VARCHAR(45) NOT NULL,
    seasons_count VARCHAR(45) NOT NULL,
    teams_count VARCHAR(45) NOT NULL,
    players_count VARCHAR(45) NOT NULL,

    PRIMARY KEY (date_generated)
);

ALTER TABLE wnba_data_user.dataset_info OWNER TO wnba_data_user;

--
-- Table structure players
--
CREATE TABLE IF NOT EXISTS  players (
    player_id VARCHAR(45) NOT NULL,
    player_name VARCHAR(45) NOT NULL,
    active_flag VARCHAR(45) NOT NULL,
    rookie_season VARCHAR(45) NOT NULL,
    last_season VARCHAR(45) NOT NULL,
    unknown VARCHAR(45) NOT NULL,
    current_team VARCHAR(45) NOT NULL,

    PRIMARY KEY (player_id)
);

ALTER TABLE wnba_data_user.players OWNER TO wnba_data_user;


--
-- Table structure common_team_roster
--
CREATE TABLE IF NOT EXISTS common_team_roster(
    TeamID VARCHAR(45) NOT NULL,
    SEASON VARCHAR(45) NOT NULL,
    LeagueID VARCHAR(45) NOT NULL,
    PLAYER VARCHAR(45) NOT NULL,
    NICKNAME VARCHAR(45) NOT NULL,
    PLAYER_SLUG VARCHAR(45) NOT NULL,
    NUM VARCHAR(45) NOT NULL,
    POSITION VARCHAR(45),
    HEIGHT VARCHAR(45),
    WEIGHT VARCHAR(45),
    BIRTH_DATE VARCHAR(45),
    AGE VARCHAR(45),
    EXP VARCHAR(45),
    SCHOOL VARCHAR(45),
    PLAYER_ID VARCHAR(45) NOT NULL,
    HOW_ACQUIRED VARCHAR(45),
    PRIMARY KEY (PLAYER_ID)
);

ALTER TABLE wnba_data_user.common_team_roster OWNER TO wnba_data_user;


--
-- Table structure player_career_stats
--
CREATE TABLE IF NOT EXISTS  player_career_stats (
    PLAYER_ID VARCHAR(45) NOT NULL,
    SEASON_ID VARCHAR(45) NOT NULL,
    LEAGUE_ID VARCHAR(45) NOT NULL,
    TEAM_ID VARCHAR(45) NOT NULL,
    TEAM_ABBREVIATION VARCHAR(45) NOT NULL,
    PLAYER_AGE VARCHAR(45) NOT NULL,
    GP VARCHAR(45) NOT NULL,
    GS VARCHAR(45) NOT NULL,
    MIN VARCHAR(45) NOT NULL,
    FGM VARCHAR(45) NOT NULL,
    FGA VARCHAR(45) NOT NULL,
    FG_PCT VARCHAR(45) NOT NULL,
    FG3M VARCHAR(45) NOT NULL,
    FG3A VARCHAR(45) NOT NULL,
    FG3_PCT VARCHAR(45) NOT NULL,
    FTM VARCHAR(45) NOT NULL,
    FTA VARCHAR(45) NOT NULL,
    FT_PCT VARCHAR(45) NOT NULL,
    OREB VARCHAR(45) NOT NULL,
    DREB VARCHAR(45) NOT NULL,
    REB VARCHAR(45) NOT NULL,
    AST VARCHAR(45) NOT NULL,
    STL VARCHAR(45) NOT NULL,
    BLK VARCHAR(45) NOT NULL,
    TOV VARCHAR(45) NOT NULL,
    PF VARCHAR(45) NOT NULL,
    PTS VARCHAR(45) NOT NULL,

    PRIMARY KEY (PLAYER_ID)
);

ALTER TABLE wnba_data_user.player_career_stats OWNER TO wnba_data_user;


--
-- Table structure player_game_logs
--
CREATE TABLE IF NOT EXISTS  player_game_logs (
    SEASON_YEAR INT NOT NULL,
    PLAYER_ID INT NOT NULL,
    PLAYER_NAME VARCHAR(45) NOT NULL,
    NICKNAME VARCHAR(45) NOT NULL,
    TEAM_ID INT NOT NULL,
    TEAM_ABBREVIATION VARCHAR(45) NOT NULL,
    TEAM_NAME VARCHAR(45) NOT NULL,
    GAME_ID INT NOT NULL,
    GAME_DATE TIMESTAMP NOT NULL,
    MATCHUP VARCHAR(45) NOT NULL,
    WL VARCHAR(45) NOT NULL,
    MIN VARCHAR(45) NOT NULL,
    FGM VARCHAR(45) NOT NULL,
    FGA VARCHAR(45) NOT NULL,
    FG_PCT VARCHAR(45) NOT NULL,
    FG3M VARCHAR(45) NOT NULL,
    FG3A VARCHAR(45) NOT NULL,
    FG3_PCT VARCHAR(45) NOT NULL,
    FTM VARCHAR(45) NOT NULL,
    FTA VARCHAR(45) NOT NULL,
    FT_PCT VARCHAR(45) NOT NULL,
    OREB VARCHAR(45) NOT NULL,
    DREB VARCHAR(45) NOT NULL,
    REB VARCHAR(45) NOT NULL,
    AST VARCHAR(45) NOT NULL,
    TOV VARCHAR(45) NOT NULL,
    STL VARCHAR(45) NOT NULL,
    BLK VARCHAR(45) NOT NULL,
    BLKA VARCHAR(45) NOT NULL,
    PF VARCHAR(45) NOT NULL,
    PFD VARCHAR(45) NOT NULL,
    PTS VARCHAR(45) NOT NULL,
    PLUS_MINUS VARCHAR(45) NOT NULL,
    NBA_FANTASY_PTS VARCHAR(45) NOT NULL,
    DD2 VARCHAR(45) NOT NULL,
    TD3 VARCHAR(45) NOT NULL,
    WNBA_FANTASY_PTS VARCHAR(45) NOT NULL,
    GP_RANK VARCHAR(45) NOT NULL,
    W_RANK VARCHAR(45) NOT NULL,
    L_RANK VARCHAR(45) NOT NULL,
    W_PCT_RANK VARCHAR(45) NOT NULL,
    MIN_RANK VARCHAR(45) NOT NULL,
    FGM_RANK VARCHAR(45) NOT NULL,
    FGA_RANK VARCHAR(45) NOT NULL,
    FG_PCT_RANK VARCHAR(45) NOT NULL,
    FG3M_RANK VARCHAR(45) NOT NULL,
    FG3A_RANK VARCHAR(45) NOT NULL,
    FG3_PCT_RANK VARCHAR(45) NOT NULL,
    FTM_RANK VARCHAR(45) NOT NULL,
    FTA_RANK VARCHAR(45) NOT NULL,
    FT_PCT_RANK VARCHAR(45) NOT NULL,
    OREB_RANK VARCHAR(45) NOT NULL,
    DREB_RANK VARCHAR(45) NOT NULL,
    REB_RANK VARCHAR(45) NOT NULL,
    AST_RANK VARCHAR(45) NOT NULL,
    TOV_RANK VARCHAR(45) NOT NULL,
    STL_RANK VARCHAR(45) NOT NULL,
    BLK_RANK VARCHAR(45) NOT NULL,
    BLKA_RANK VARCHAR(45) NOT NULL,
    PF_RANK VARCHAR(45) NOT NULL,
    PFD_RANK VARCHAR(45) NOT NULL,
    PTS_RANK VARCHAR(45) NOT NULL,
    PLUS_MINUS_RANK VARCHAR(45) NOT NULL,
    NBA_FANTASY_PTS_RANK VARCHAR(45) NOT NULL,
    DD2_RANK VARCHAR(45) NOT NULL,
    TD3_RANK VARCHAR(45) NOT NULL,
    WNBA_FANTASY_PTS_RANK VARCHAR(45) NOT NULL,
    AVAILABLE_FLAG VARCHAR(45) NOT NULL,
	MIN_SEC VARCHAR(45) NOT NULL,
    PRIMARY KEY (GAME_ID)
);

ALTER TABLE wnba_data_user.player_game_logs OWNER TO wnba_data_user;


--
-- Table structure season_totals_regular_season
--
CREATE TABLE IF NOT EXISTS  season_totals_regular_season (
    PLAYER_ID VARCHAR(45) NOT NULL,
    SEASON_ID VARCHAR(45) NOT NULL,
    LEAGUE_ID VARCHAR(45) NOT NULL,
    TEAM_ID VARCHAR(45) NOT NULL,
    TEAM_ABBREVIATION VARCHAR(45) NOT NULL,
    PLAYER_AGE VARCHAR(45) NOT NULL,
    GP VARCHAR(45) NOT NULL,
    GS VARCHAR(45) NOT NULL,
    MIN VARCHAR(45) NOT NULL,
    FGM VARCHAR(45) NOT NULL,
    FGA VARCHAR(45) NOT NULL,
    FG_PCT VARCHAR(45) NOT NULL,
    FG3M VARCHAR(45) NOT NULL,
    FG3A VARCHAR(45) NOT NULL,
    FG3_PCT VARCHAR(45) NOT NULL,
    FTM VARCHAR(45) NOT NULL,
    FTA VARCHAR(45) NOT NULL,
    FT_PCT VARCHAR(45) NOT NULL,
    OREB VARCHAR(45) NOT NULL,
    DREB VARCHAR(45) NOT NULL,
    REB VARCHAR(45) NOT NULL,
    AST VARCHAR(45) NOT NULL,
    STL VARCHAR(45) NOT NULL,
    BLK VARCHAR(45) NOT NULL,
    TOV VARCHAR(45) NOT NULL,
    PF VARCHAR(45) NOT NULL,
    PTS VARCHAR(45) NOT NULL,

    PRIMARY KEY (PLAYER_ID)
);

ALTER TABLE wnba_data_user.season_totals_regular_season OWNER TO wnba_data_user;



--
-- Table structure teams
--
CREATE TABLE IF NOT EXISTS  teams (
    team_id VARCHAR(45) NOT NULL,
    team_abbreviation VARCHAR(45) NOT NULL,
    team_name VARCHAR(45) NOT NULL,
    team_city VARCHAR(45) NOT NULL,
    team_state VARCHAR(45) NOT NULL,
    time_zone VARCHAR(45) NOT NULL,
    primary_color VARCHAR(45) NOT NULL,
    secondary_color VARCHAR(45) NOT NULL,
    url VARCHAR(45) NOT NULL,

    PRIMARY KEY (team_id)
);

ALTER TABLE wnba_data_user.teams OWNER TO wnba_data_user;


--
-- Table structure shot_chart_detail
--
CREATE TABLE IF NOT EXISTS  shot_chart_detail(
    GRID_TYPE VARCHAR(45) NOT NULL,
    GAME_ID VARCHAR(45) NOT NULL,
    GAME_EVENT_ID VARCHAR(45) NOT NULL,
    PLAYER_ID VARCHAR(45) NOT NULL,
    PLAYER_NAME VARCHAR(45) NOT NULL,
    TEAM_ID VARCHAR(45) NOT NULL,
    TEAM_NAME VARCHAR(45) NOT NULL,
    PERIOD VARCHAR(45) NOT NULL,
    MINUTES_REMAINING VARCHAR(45) NOT NULL,
    SECONDS_REMAINING VARCHAR(45) NOT NULL,
    EVENT_TYPE VARCHAR(45) NOT NULL,
    ACTION_TYPE VARCHAR(45) NOT NULL,
    SHOT_TYPE VARCHAR(45) NOT NULL,
    SHOT_ZONE_BASIC VARCHAR(45) NOT NULL,
    SHOT_ZONE_AREA VARCHAR(45) NOT NULL,
    SHOT_ZONE_RANGE VARCHAR(45) NOT NULL,
    SHOT_DISTANCE VARCHAR(45) NOT NULL,
    LOC_X VARCHAR(45) NOT NULL,
    LOC_Y VARCHAR(45) NOT NULL,
    SHOT_ATTEMPTED_FLAG VARCHAR(45) NOT NULL,
    SHOT_MADE_FLAG VARCHAR(45) NOT NULL,
    GAME_DATE VARCHAR(45) NOT NULL,
    HTM VARCHAR(45) NOT NULL,
    VTM VARCHAR(45) NOT NULL,
    PRIMARY KEY (GAME_EVENT_ID)
);

ALTER TABLE wnba_data_user.shot_chart_detail OWNER TO wnba_data_user;